# Generated by Django 3.0.3 on 2021-12-21 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=50, unique=True, verbose_name='Nombre Area')),
            ],
        ),
        migrations.CreateModel(
            name='Estatus_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_mast', models.CharField(max_length=50)),
                ('img_estatus', models.ImageField(height_field=50, upload_to='', width_field=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mant', models.CharField(max_length=100, verbose_name='Mantenimiento')),
                ('tipo', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=10)),
                ('periodo', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquina', models.CharField(max_length=100, unique=True, verbose_name='Maquina')),
                ('no_serie', models.CharField(max_length=100)),
                ('codigo_kepler', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_mant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('fecha_plan', models.DateField()),
                ('cod_kepler_prov', models.CharField(blank=True, max_length=10)),
                ('orden_compra', models.CharField(blank=True, max_length=50)),
                ('horas_plan', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notas_plan', models.TextField(blank=True, max_length=500)),
                ('mant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantt.Mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50, unique=True, verbose_name='Tipo maquina')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=50, verbose_name='tarea')),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('mant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(max_length=100)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantt.Maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Realiza_mant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizado', models.DateField()),
                ('notas_real', models.TextField(blank=True, max_length=500)),
                ('plan_mant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantt.Plan_mant')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=100, unique=True, verbose_name='Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Tipo_maquina')),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Modelo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantt.Maquina'),
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(auto_now_add=True)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Estatus_master')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantt.Maquina')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sistema_maquina',
            constraint=models.UniqueConstraint(fields=('nombre_sistema', 'maquina'), name='Cons_sistema_maquina'),
        ),
    ]
