# Generated by Django 3.0.3 on 2021-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus_master',
            name='img_estatus',
            field=models.ImageField(height_field=50, upload_to='status_master', width_field=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='periodo',
            field=models.CharField(choices=[('Unico', 'Unico'), ('Pre_uso', 'Pre Uso'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20),
        ),
    ]
