# Generated by Django 3.0.3 on 2021-12-23 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantt', '0002_auto_20211221_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mant_dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Realiza_mant_dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizado', models.DateField(default=datetime.date(2021, 12, 23))),
                ('notas_real', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=50, verbose_name='tarea')),
                ('descripcion', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='estatus_master',
            name='img_estatus',
            field=models.ImageField(upload_to='status_master', verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='periodo',
            field=models.CharField(choices=[('Unico', 'Unico'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plan_mant',
            name='cod_kepler_prov',
            field=models.CharField(blank=True, max_length=10, verbose_name='Codigo Proveedor Kepler'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('nombre_modelo', 'tipo', 'marca'), name='Cons_Modelo'),
        ),
        migrations.AddConstraint(
            model_name='plan_mant',
            constraint=models.UniqueConstraint(fields=('fecha_plan', 'mant'), name='Cons_plan_mant'),
        ),
        migrations.AddField(
            model_name='tarea_dia',
            name='mant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Mant_dia'),
        ),
        migrations.AddField(
            model_name='realiza_mant_dia',
            name='mant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantt.Mant_dia'),
        ),
        migrations.AddField(
            model_name='mant_dia',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantt.Maquina'),
        ),
        migrations.AddConstraint(
            model_name='realiza_mant_dia',
            constraint=models.UniqueConstraint(fields=('fecha_realizado', 'mant'), name='Cons_realiza_mant_dia'),
        ),
    ]
