# Generated by Django 3.0.3 on 2021-12-28 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantt', '0003_auto_20211223_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=200)),
                ('tipo_doc', models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Instructivo', 'Instructivo'), ('Otro', 'Otro')], max_length=40)),
                ('documento', models.FileField(upload_to='docs_master')),
                ('ruta_sharepoint', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='tarea_dia',
            name='vinculo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='realiza_mant_dia',
            name='fecha_realizado',
            field=models.DateField(default=datetime.date(2021, 12, 28)),
        ),
        migrations.AddConstraint(
            model_name='mant_dia',
            constraint=models.UniqueConstraint(fields=('maquina',), name='Cons_mant_dia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantt.Maquina'),
        ),
    ]
