# Generated by Django 3.0.3 on 2022-01-04 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantt', '0004_auto_20211228_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['maquina', 'periodo']},
        ),
        migrations.AlterModelOptions(
            name='plan_mant',
            options={'ordering': ['mant__maquina__modelo__tipo__area', 'mant__maquina__nombre_maquina']},
        ),
        migrations.AddField(
            model_name='maquina',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='realiza_mant_dia',
            name='fecha_realizado',
            field=models.DateField(default=datetime.date(2022, 1, 4)),
        ),
    ]
