# Generated by Django 3.0.3 on 2022-01-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantt', '0005_auto_20220104_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='maquina_master'),
        ),
    ]
