from mantt.views.ini_mant import *
from mantt.views.maquinas import *
from mantt.views.documentos import *
from mantt.views.planes_mant import *
from mantt.views.estatus import *
from mantt.views.tareas import *
from mantt.views.cat_mants import *
from mantt.views.realiza_mant import *
from mantt.views.graficos import *